# Generated by Django 3.2.5 on 2021-07-31 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fighter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=100)),
                ('height', models.IntegerField()),
                ('arm_reach', models.IntegerField()),
                ('leg_reach', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('active', models.BooleanField()),
                ('hometown', models.CharField(max_length=100)),
                ('trains_at', models.CharField(max_length=200)),
                ('fighting_style', models.CharField(max_length=100)),
                ('debut', models.DateField()),
                ('record_wins', models.IntegerField()),
                ('record_losses', models.IntegerField()),
                ('record_draws', models.IntegerField()),
                ('record_nc', models.IntegerField()),
                ('wins_by_ko', models.IntegerField()),
                ('wins_by_sub', models.IntegerField()),
                ('win_by_dec', models.IntegerField()),
                ('grappling_accuracy', models.IntegerField()),
                ('takedown_landed', models.IntegerField()),
                ('takedown_attempted', models.IntegerField()),
                ('takedown_per_15_minutes', models.FloatField()),
                ('sub_average_per_15_minutes', models.FloatField()),
                ('takedown_defense', models.IntegerField()),
                ('striking_accuracy', models.IntegerField()),
                ('strikes_landed', models.IntegerField()),
                ('strikes_attempted', models.IntegerField()),
                ('sigificant_strikes_landed_per_minute', models.FloatField()),
                ('sigificant_strikes_absorbed_per_minute', models.FloatField()),
                ('sigificant_strikes_defense', models.IntegerField()),
                ('knockdown_ratio', models.FloatField()),
                ('average_fight_time', models.TimeField()),
                ('ranking', models.IntegerField(blank=True)),
                ('champion', models.BooleanField()),
            ],
        ),
    ]
